---
- name: "{{ action }} extra soft"
  apt:
    name: "{{ item.1 }}"
    state: "{{ state }}"
  with_nested:
    - "{{ outer_item.group }}"
    - "{{ outer_item.elt }}"
  when:
    - item.0 in group_names
